# Generated by Django 5.1 on 2024-09-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_site', '0002_amenitydata_apartment_apartmentspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitydata',
            name='accessible',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='amenitydata',
            name='heating',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='amenitydata',
            name='kitchen',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='amenitydata',
            name='shower',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='amenitydata',
            name='tv',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='amenitydata',
            name='wifi',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='apartmentspace',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartmentspace',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartmentspace',
            name='max_people',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
