# Generated by Django 5.1 on 2024-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_site', '0003_amenitydata_accessible_amenitydata_heating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmenityData',
        ),
        migrations.DeleteModel(
            name='ApartmentSpace',
        ),
        migrations.AddField(
            model_name='apartment',
            name='accessible',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='heating',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='kitchen',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='max_people',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='shower',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tv',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='wifi',
            field=models.BooleanField(default=0),
        ),
    ]
