# Generated by Django 5.1 on 2024-09-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_site', '0004_delete_amenitydata_delete_apartmentspace_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='street_name',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='images',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='street_no',
        ),
        migrations.AddField(
            model_name='apartment',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='apartment',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='apartment',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
