# Generated by Django 5.1 on 2024-09-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_site', '0006_remove_apartment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='contact_person',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='phone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
